// <auto-generated />
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(BackendAPIContext))]
    [Migration("20250211034557_TeamsDataUpdate")]
    partial class TeamsDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("VotingApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneralId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneralId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("VotingApp.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessLoginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneralId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusinessId");

                    b.HasIndex("BusinessLoginId");

                    b.HasIndex("GeneralId");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("VotingApp.Models.BusinessLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessLogin");
                });

            modelBuilder.Entity("VotingApp.Models.FinalTeamScores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Teams_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FinalTeamScores");
                });

            modelBuilder.Entity("VotingApp.Models.General", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Admin_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessLogin_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffCoach_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Voter_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("General");
                });

            modelBuilder.Entity("VotingApp.Models.StaffCoach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffCoachType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneralId");

                    b.ToTable("StaffCoach");
                });

            modelBuilder.Entity("VotingApp.Models.TeamData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amazement")
                        .HasColumnType("REAL");

                    b.Property<float>("Communication")
                        .HasColumnType("REAL");

                    b.Property<float>("Creativity")
                        .HasColumnType("REAL");

                    b.Property<float>("Performance")
                        .HasColumnType("REAL");

                    b.Property<float>("Professionalism")
                        .HasColumnType("REAL");

                    b.Property<int>("Teams_id")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Theme")
                        .HasColumnType("REAL");

                    b.Property<float>("VisualDesign")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TeamData");
                });

            modelBuilder.Entity("VotingApp.Models.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompeteLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalTeamScoresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VotesReceived")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinalTeamScoresId");

                    b.HasIndex("TeamDataId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("VotingApp.Models.Admin", b =>
                {
                    b.HasOne("VotingApp.Models.General", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General");
                });

            modelBuilder.Entity("VotingApp.Models.Business", b =>
                {
                    b.HasOne("VotingApp.Models.BusinessLogin", "BusinessLogin")
                        .WithMany()
                        .HasForeignKey("BusinessLoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingApp.Models.General", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessLogin");

                    b.Navigation("General");
                });

            modelBuilder.Entity("VotingApp.Models.StaffCoach", b =>
                {
                    b.HasOne("VotingApp.Models.General", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General");
                });

            modelBuilder.Entity("VotingApp.Models.Teams", b =>
                {
                    b.HasOne("VotingApp.Models.FinalTeamScores", "FinalTeamScores")
                        .WithMany()
                        .HasForeignKey("FinalTeamScoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingApp.Models.TeamData", "TeamData")
                        .WithMany()
                        .HasForeignKey("TeamDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalTeamScores");

                    b.Navigation("TeamData");
                });
#pragma warning restore 612, 618
        }
    }
}
